authors:
  paul:
    display_name: Paul Barrett
    email: paul.barrett@chembiohub.ox.ac.uk
    github: paulbarrett79
  michael:
    display_name: Michael O'Hagan
    email: info@chembiohub.ox.ac.uk
    github: michaelohagan
  karen:
    display_name: Karen Porter
    email: karen.porter@chembiohub.ox.ac.uk
    github: karenporter
  andy:
    display_name: Andrew Stretton
    email: andrew.stretton@chembiohub.ox.ac.uk
    github: strets123
  anthony:
    display_name: Anthony Bradley
    email: oommppaa.help@gmail.com
    github: abradle
  adam:
    display_name: Adam Hendry
    email: adam.hendry@chembiohub.ox.ac.uk
    github: aekhendry
  oakley:
    display_name: Oakley Cox
    email: oakley.cox@keble.ox.ac.uk
    github: ""

name: Chembio Hub Blog
title: ChemBio Hub Website
description: A team blog about the technology and stories behind the chembio hub project
url: https://chembiohub.ox.ac.uk
non_https_url: http://chembiohub.ox.ac.uk

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

excerpt_separator: "<!-- more -->"
permalink: /blog/:year/:month/:day/:title.html

events:
  - title: "Chemical biology across the University of Oxford"
    subtitle: "A symposium by ChemBio Hub to strengthen interdepartmental research connections"
    date_start: "2014-11-10"
    date_end: "2014-11-10"
    link: "/symposium2014"

  - title: "Current expertise and future directions in drug discovery"
    subtitle: "An Oxford-Industry conversation"
    date_start: "2015-07-31"
    date_end: "2015-07-31"
    link: "/conversation"

tools:
  internal:
    - key: 'chemreg'
      title: "ChemReg"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: "/chemreg"
      cbh_link: "http://chembiohub.ox.ac.uk/hub/webauth"
      github_link: "https://github.com/thesgc/chembiohub_ws"
      other_repo_link: ""
      thumbnail: "data-chemreg.png"
    - key: 'invreg'
      title: "InventoryReg"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: "/inventoryreg"
      cbh_link: "http://chembiohub.ox.ac.uk/hub/webauth"
      github_link: "https://github.com/thesgc/chembiohub_ws"
      other_repo_link: ""
      thumbnail: "data-chemreg.png"
    - key: 'assayreg'
      title: "AssayReg"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: "/assayreg"
      cbh_link: "http://staging.chembiohub.ox.ac.uk/test/webauth"
      github_link: "https://github.com/thesgc/chembiohub_assay"
      other_repo_link: ""
      thumbnail: "data-chemreg.png"
    - key: 'crunch'
      title: "Crunch"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: "/crunch"
      cbh_link: "http://chembiohub.ox.ac.uk/crunch/webauth"
      github_link: "https://github.com/thesgc/chembiocrunch"
      other_repo_link: ""
      thumbnail: "data-chemreg.png"
  external:
    - key: 'wonka'
      title: "WONKA"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: ""
      cbh_link: "http://wonka.sgc.ox.ac.uk/WONKA"
      github_link: ""
      other_repo_link: "https://bitbucket.org/abradley/wonka/fork"
      thumbnail: "wonka.png"
    - key: 'oommppaa'
      title: "OOMMPPAA"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: ""
      cbh_link: "http://oommppaa.sgc.ox.ac.uk/OOMMPPAA/"
      github_link: ""
      other_repo_link: "https://bitbucket.org/abradley/oommppaa/fork"
      thumbnail: "oommppaa.png"
    - key: 'res_equip'
      title: "Research Equipment Database"
      tagline: "tagline here"
      description: "Descriptive paragraph here with links and contact info"
      info_link: ""
      cbh_link: "https://www.research-facilities.ox.ac.uk/browse"
      github_link: ""
      other_repo_link: ""
      thumbnail: "res_equip.png"

equipment_categories:
  - link: "/other/biobank/"
    label: "Biobank"
  - link: "/biomolecular-interaction-analysis/"
    label: "Biomolecular Interaction Analysis"
  - link: "/gas-liquid-analysis/biochemical-analysis/"
    label: "Biochemical Analysis"
  - link: "/cell-nucleic-acid-protein-analysis/"
    label: "Cell / Nucleic Acid / Protein Analysis"
  - link: "/cell-preparation/"
    label: "Cell Preparation"
  - link: "/cell-based-assays/"
    label: "Cell-based assays"
  - link: "/chromatography/"
    label: "Chromatography"
  - link: "/other/fermentation/"
    label: "Fermentation"
  - link: "/other/freeze-drying/"
    label: "Freeze Drying"
  - link: "/gas-liquid-chromatography-mass-spectrometry/"
    label: "GC-MS / LC-MS"
  - link: "/sample-analysis/hplc/"
    label: "HPLC"
  - link: "/genetic-techniques/"
    label: "Genetic Techniques"
  - link: "/imaging/"
    label: "Imaging"
  - link: "/liquid-sample-handling/"
    label: "Liquid / Sample Handling"
  - link: "/microarrays/"
    label: "Microarrays"
  - link: "/other/microwave-synthesis/"
    label: "Microwave Synthesis"
  - link: "/sample-analysis/nmr/"
    label: "NMR"
  - link: "/other/protein-preparation/"
    label: "Protein Preparation"
  - link: "/other/peptide-synthesis/"
    label: "Peptide Synthesis"
  - link: "/browse/plate-reader/"
    label: "Plate Reader"
  - link: "/qpcr/"
    label: "qPCR"
  - link: "/sample-prep/"
    label: "Sample Prep"
  - link: "/spectroscopy/"
    label: "Spectroscopy"



