speakers:
  - first_name: Angela
    last_name: Russell
    email: ""
    link: "http://www.pharm.ox.ac.uk/research/angela-russell"
    photo: "/assets/img/people/Angela_Russell_Chem.png"
    dept: "Oncology"
    talk_title: Drug screening for Duchenne Muscular Dystrophy
    embed_code: ""
    talk_order: 12

  - first_name: Benedikt
    last_name: Kessler
    email: ""
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/benedikt-kessler
    photo: /assets/img/people/Benedikt_Kessler_TDI.png
    dept: TDI
    talk_title: Chemical probes and applications in the ubiquitin system
    embed_code: ""
    talk_order: 14

  - first_name: Brian 
    last_name: Marsden
    email: brian.marsden@sgc.ox.ac.uk
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/brian-marsden
    photo: /assets/img/people/Brian_Marsden_SGC.png
    dept: SGC
    talk_title: Chemical Biology across The University
    embed_code: "Marsden.pptx"
    talk_order: 1

  - first_name: Chas 
    last_name: Bountra
    email: chas.bountra@sgc.ox.ac.uk
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/chas-bountra
    photo: /assets/img/people/Chas_Bountra_SGC.png
    dept: SGC
    talk_title: Title TBC
    embed_code: ""
    talk_order: 3

  - first_name: Chris 
    last_name: Schofield
    email: ""
    link: http://www.chem.ox.ac.uk/oc/cjschofield/
    photo: /assets/img/people/Chris_Schofield_Chem.png
    dept: Chemistry
    talk_title: Chemical Biology – starting points for discussion
    embed_code: "Schofield.pptx"
    talk_order: 2

  - first_name: Daniel 
    last_name: Ebner
    email: ""
    link: http://www.tdi.ox.ac.uk/staff
    photo: /assets/img/people/Daniel_Ebner_TDI.png
    dept: TDI
    talk_title: Cell-based phenotypic screening at the Target Discovery Institute
    embed_code: ""
    talk_order: 4

  - first_name: Geoff 
    last_name: Higgins
    email: ""
    link: http://www.oncology.ox.ac.uk/research/geoff-higgins-1
    photo: /assets/img/people/Geoff_Higgins_Oncology.png
    dept: Oncology
    talk_title: Identification of drug targets to increase tumour radio sensitivity
    embed_code: ""
    talk_order: 9

  - first_name: Grigory 
    last_name: Dianov
    email: ""
    link: http://www.oncology.ox.ac.uk/research/grigory-dianov/
    photo: /assets/img/people/Grigory_Dianov_Oncology.png
    dept: Oncology
    talk_title: Title TBC
    embed_code: ""
    talk_order: 14

  - first_name: Karen 
    last_name: Porter
    email: karen@chembiohub.ox.ac.uk
    link: ""
    photo: /assets/img/people/Karen_Porter_CBH.png
    dept: ChemBio Hub
    talk_title: The ChemBio Hub project - supporting world class chemical biology research
    embed_code: "Porter.pptx"
    talk_order: 8

  - first_name: Kay 
    last_name: Davies
    email: ""
    link: http://www.dpag.ox.ac.uk/team/group-leaders/kay-davies
    photo: /assets/img/people/Kay_Davies_DPAG.png
    dept: DPAG
    talk_title: Title TBC
    embed_code: ""
    talk_order: 12

  - first_name: Nicole 
    last_name: Zitzmann
    email: ""
    link: http://www.bioch.ox.ac.uk/aspsite/index.asp?pageid=608
    photo: /assets/img/people/Nicole_Zitzmann_Biochem.png
    dept: Biochemistry
    talk_title: Iminosugars as antivirals
    embed_code: ""
    talk_order: 11

  - first_name: Paul 
    last_name: Brennan
    email: paul.brennan@sgc.ox.ac.uk
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/paul-brennan
    photo: /assets/img/people/Paul_brennan_SGC.png
    dept: SGC
    talk_title: Chemical probes for epigenetic proteins
    embed_code: "Brennan.pdf"
    talk_order: 6

  - first_name: Stefan 
    last_name: Knapp
    email: stefan.knapp@sgc.ox.ac.uk
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/stefan-knapp
    photo: /assets/img/people/Stefan_Knapp_TDI.png
    dept: TDI
    talk_title: Title TBC
    embed_code: ""
    talk_order: 11

  - first_name: Stuart 
    last_name: Conway
    email: ""
    link: http://research.chem.ox.ac.uk/stuart-conway.aspx
    photo: /assets/img/people/Stuart_Conway_Chem.png
    dept: Chemistry
    talk_title: Hypoxia-activated prodrugs
    embed_code: ""
    talk_order: 5

  - first_name: Tom 
    last_name: Brown
    email: ""
    link: http://www.oncology.ox.ac.uk/research/professor-tom-brown
    photo: /assets/img/people/Tom_Brown_Oncology.png
    dept: Oncology
    talk_title: Extending the boundaries of nucleic acid chemistry
    embed_code: "Brown.pptx"
    talk_order: 7

  - first_name: Tom 
    last_name: Milne
    email: ""
    link: http://www.imm.ox.ac.uk/thomas-milne
    photo: /assets/img/people/Tom_Milne_WIMM.png
    dept: WIMM
    talk_title: Title TBC
    embed_code: ""
    talk_order: 13

  - first_name: Grant
    last_name: Churchill
    email: ""
    link: http://www.pharm.ox.ac.uk/research/grant-churchill
    photo: /assets/img/people/Grant_Churchill_Pharma.png
    dept: WIMM
    talk_title: Title TBC
    embed_code: ""
    talk_order: 14

  - first_name: Graham
    last_name: Wynne
    email: ""
    link: http://davies.chem.ox.ac.uk/medchem_team.aspx
    photo: /assets/img/people/Graham_Wynne_Chem.png
    dept: WIMM
    talk_title: "Small Molecule Utrophin Modulators: Towards a Therapy for Duchenne Muscular Dystrophy"
    embed_code: "Wynne.pdf"
    talk_order: 15

  - first_name: Susanne 
    last_name: Muller Knapp
    email: susanne.muller-knapp@sgc.ox.ac.uk
    link: http://www.ndm.ox.ac.uk/principal-investigators/researcher/susanne-muller-knapp
    photo: /assets/img/people/Susanne_Muller_Knapp_SGC.png
    dept: SGC
    talk_title: A chemical probe for the chromatin remodeller BAZ2B and its potential application
    embed_code: ""
    talk_order: 13
  
  - first_name: Richard 
    last_name: Wade Martins
    email: ""
    link: http://www.dpag.ox.ac.uk/research/wade-martins-group
    photo: /assets/img/people/Richard_Wade_Martins_DPAG.png
    dept: DPAG
    talk_title: Identifying novel small molecule therapeutics by cell phenotype screening - three short stories from brain and heart
    embed_code: ""
    talk_order: 10

casestudies:
  - name: "Robert Mifflin"
    dept: "Department of Physiology, Anatomy and Genetics"
    role: "Mortuary Supervisor"
    bodytext: > #  
      A service within the Department of Physiology, Anatomy and Genetics (DPAG) was in need of a centralised database to catalogue samples. 
      This system needed to be accessible to researchers who require the data for lesson planning. Their current system did not allow images 
      of the sample to be uploaded and it was difficult to update and navigate through the data that was there. By uploading their data and 
      attaching their image files into InventoryReg, we have demonstrated that it is now possible to quickly access and view teaching samples. 
      It is also possible to search information intelligently by sorting based on date added, location, sample type and so on. For those 
      searching through chemical projects it is possible to use substructure searches to find compounds and even combine this with additional 
      text based searching. Since trialing our system, this DPAG service has demonstrated increased accessibility of its teaching resources.
    quote: > #
      “The ChemBio Hub platform allows us to catalogue and maintain our samples from any computer. The ability for us to manage user 
      permissions ensures we can easily give access to researchers who want to use our resources, whilst ensuring the security of our data”
  
  - name: "Professor James McCullagh"
    dept: "Department of Chemistry"
    role: "Head of the Mass Spectrometry Research Facility"
    bodytext: > #  
      A service facility within the Chemistry Department had an extensive library of compounds that they needed to locate manually when required. 
      By uploading their chemical data into the ChemBio Hub system, they can now search for a chemical via text or substructure search. 
      This improves their laboratory productivity and saves money by allowing them to check what they have in stock.
    quote: > #
      “The ChemBio Hub platform has proven to be an effective way to manage our compound inventory. Thanks to its high flexibility, we are also 
      testing its ability to digitise our facilities sample submission process”
  
  - name: "Dr Hidenori Someya"
    dept: "Department of Chemistry"
    role: "Postdoctoral Researcher"
    bodytext: > #  
      A large group with more than 50 laboratory members based in the University of Oxford Chemistry Department had been looking for a new 
      chemical registration tool to replace their previous database. A barrier to adopting a more modern system had been the time and effort 
      required to manually transfer the 2400 compounds from one system to another. Using the ChemBio Hub .SDF file upload feature it was 
      possible to register all existing compounds quickly and easily.
    quote: > #
      “Since adopting the ChemBio Hub I have found it much easier to find chemicals in our inventory that would have been previously 
      difficult to discover. This helps me to be more productive in my working day”
  
  - name: "Professor Darren Dixon"
    dept: "Department of Chemistry"
    role: "Head of Dixon Group Research"
    bodytext: > #  
      A recently established Chemistry Doctoral Training Programme (CDT) takes a cohort of 30 students every year. These students participate 
      in two laboratory placements across the University per year, each synthesising unique compounds in separate laboratories. The programme 
      required a data management system that ensured all compound structures and their corresponding data were securely stored and tractable, 
      so that at any point they might be searched and retrieved. All students are funded by external industrial partners who demand a high 
      level of data security and require access to the students’ data. By adopting the ChemiReg platform the CDT coordinators are able to 
      securely manage and collate their student data within the same project, despite them being placed in different laboratories. They have 
      also invited their external collaborators to the project, providing them with access to the data they need.
    quote: > #
      “The ChemBio Hub has been effective in helping the CDT to manage and organise the compounds they make. This will make tracking progress 
      and communicating with sponsors much easier in the future”
  
  - name: "Professor Renier van der Hoorn"
    dept: "Department of Plant Sciences"
    role: "Associate Professor Plant Sciences"
    bodytext: > #  
      Plant Sciences is one of  seven departments across the University of Oxford which have created projects organizing data ranging from 
      plasmids and antibodies to generic ordering and experimental results. This highlights both the flexibility of the system and the ease 
      with which it can manipulate data in multiple formats. For example, one Plant Science Department research group has created 7 projects 
      to organise the various inventories they maintain, ranging from plasmids and mutant seed lines to compounds and antibodies.
    quote: > #
      “The ChemBio Hub system allows us to quickly upload and manage numerous inventories. Having easy access to this data in the laboratory 
      will make my group’s lives easier and more productive”
  
  - name: "Ms Marta Jagielowicz"
    dept: "Nuffield Department of Medicine"
    role: "Laboratory Manager"
    bodytext: ""
    quote: > #
      "The ChemBio Hub lets me manage multiple inventories. This means whenever I need to look for something I can find it all in the same place"
